In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print("Python environment is working!")
print("Pandas version:", pd.__version__)

Python environment is working!
Pandas version: 3.0.5

In [3]:
import yfinance as yf

ticker = "AAPL"

data = yf.download(
    ticker,
    start="2020-01-01",
    end="2025-01-01",
    auto_adjust=True
)

data.head()

[*********************100%***********************]  1 of 1 completed

Price           Close       High        Low       Open     Volume
Ticker           AAPL       AAPL       AAPL       AAPL       AAPL
Date
2020-01-02  72.271538  72.331694  71.029915  71.282568  135480400
2020-01-03  71.568932  72.326897  71.345153  71.501557  146322800
2020-01-06  72.139168  72.177669  70.442769  70.693021  118387200
2020-01-07  71.799927  72.403889  71.580958  72.148828  108872000
2020-01-08  72.954918  73.255698  71.503953  71.503953  132079200

In [4]:
# Save AAPL data to the project's data folder
data.to_csv("../data/AAPL.csv")

print("AAPL data saved successfully!")

AAPL data saved successfully!

In [5]:
# Load the saved AAPL data
aapl_loaded = pd.read_csv("../data/AAPL.csv", index_col=0, parse_dates=True)

# Display the first 5 rows
aapl_loaded.head()

/var/folders/16/k7myh9ys39z527mkrtdrkmzr0000gn/T/ipykernel_72472/961895835.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  aapl_loaded = pd.read_csv("../data/AAPL.csv", index_col=0, parse_dates=True)

,Close,High,Low,Open,Volume
Price,,,,,
Ticker,AAPL,AAPL,AAPL,AAPL,AAPL
Date,NaN,NaN,NaN,NaN,NaN
2020-01-02,72.27153778076172,72.3316938789073,71.02991503384398,71.28256770874596,135480400
2020-01-03,71.56893157958984,72.32689716209705,71.34515259353762,71.50155702432866,146322800
2020-01-06,72.13916778564453,72.17766855781666,70.44276927666618,70.69302062414934,118387200

In [6]:
# Check the shape of the saved AAPL dataset
print("Rows and columns:", aapl_loaded.shape)

# Check the column names
print("\nColumns:")
print(aapl_loaded.columns)

Rows and columns: (1260, 5)

Columns:
Index(['Close', 'High', 'Low', 'Open', 'Volume'], dtype='str')